<a href="https://colab.research.google.com/github/AhmadMelhem25/AI-HUb-/blob/main/AI_COURSE_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
list1=[
        {"name":"ali","age":20,"city":"Amman"},
        {"name":"omar","age":30,"city":"Amman"},
        {"name":"omar","age":30,"city":"Amman"}
       ]

In [ ]:
list2=[
        ["ali",20,"Amman"],
        ["omar",30,"Amman"],
        ["omar",30,"Amman"]

       ]

In [ ]:
pd.DataFrame(list1)

   name  age   city
0   ali   20  Amman
1  omar   30  Amman
2  omar   30  Amman

In [ ]:
pd.DataFrame(list2)

      0   1      2
0   ali  20  Amman
1  omar  30  Amman
2  omar  30  Amman

In [ ]:
df=pd.DataFrame(list2)

In [ ]:
df.columns=["name","age","city"]

In [ ]:
pd.DataFrame(df)

   name  age   city
0   ali   20  Amman
1  omar   30  Amman
2  omar   30  Amman

In [ ]:
df.loc[2]

name     omar
age        30
city    Amman
Name: 2, dtype: object

In [ ]:
data=pd.read_csv("/company.csv")

In [ ]:
data

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
0,8675,Bachelors,2017,Amman,34,Male,500.0,0.0,yes
1,1531,Bachelors,2013,Irbid,28,Female,560.0,3.0,no
2,3028,PHD,2014,Irbid,38,Female,1000.0,2.0,no
3,2203,Masters,2016,Irbid,27,Female,800.0,5.0,NaN
4,4848,Masters,2017,Amman,24,Male,800.0,2.0,yes
5,6877,Bachelors,2016,Amman,22,Male,550.0,0.0,yes
6,2012,Bachelors,2015,Irbid,38,Male,550.0,0.0,no
7,8886,Bachelors,2016,Aqaba,34,Female,550.0,2.0,no
8,8741,Bachelors,2016,Amman,23,Male,550.0,1.0,no
9,6789,Masters,2017,Amman,37,Male,900.0,2.0,no
10,9872,Masters,2012,Amman,27,Male,800.0,5.0,no
11,2017,Bachelors,2016,Amman,34,Male,700.0,3.0,no
12,3018,PHD,2018,Irbid,32,Male,1500.0,5.0,no
13,1056,Bachelors,2016,Aqaba,39,Male,560.0,2.0,no
14,6845,Bachelors,2012,Irbid,37,Male,NaN,NaN,yes
15,4245,Bachelors,2017,Irbid,29,Female,500.0,3.0,no
16,6688,Bachelors,2014,Amman,34,Female,550.0,2.0,no
17,9764,Bachelors,2014,Amman,34,Male,600.0,4.0,no
18,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no
19,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no
20,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no
21,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no

In [ ]:
data.shape

(22, 9)

In [ ]:
data.head(5)

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
0,8675,Bachelors,2017,Amman,34,Male,500.0,0.0,yes
1,1531,Bachelors,2013,Irbid,28,Female,560.0,3.0,no
2,3028,PHD,2014,Irbid,38,Female,1000.0,2.0,no
3,2203,Masters,2016,Irbid,27,Female,800.0,5.0,NaN
4,4848,Masters,2017,Amman,24,Male,800.0,2.0,yes

In [ ]:
data.tail()

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
17,9764,Bachelors,2014,Amman,34,Male,600.0,4.0,no
18,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no
19,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no
20,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no
21,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no

In [ ]:
data.loc[15:20]

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
15,4245,Bachelors,2017,Irbid,29,Female,500.0,3.0,no
16,6688,Bachelors,2014,Amman,34,Female,550.0,2.0,no
17,9764,Bachelors,2014,Amman,34,Male,600.0,4.0,no
18,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no
19,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no
20,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no

In [ ]:
data.iloc[15:17]

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
15,4245,Bachelors,2017,Irbid,29,Female,500.0,3.0,no
16,6688,Bachelors,2014,Amman,34,Female,550.0,2.0,no

In [ ]:
data["Education"]

0     Bachelors
1     Bachelors
2           PHD
3       Masters
4       Masters
5     Bachelors
6     Bachelors
7     Bachelors
8     Bachelors
9       Masters
10      Masters
11    Bachelors
12          PHD
13    Bachelors
14    Bachelors
15    Bachelors
16    Bachelors
17    Bachelors
18    Bachelors
19    Bachelors
20    Bachelors
21    Bachelors
Name: Education, dtype: object

In [ ]:
data.isnull().sum()

id             0
Education      0
JoiningYear    0
City           0
Age            0
Gender         0
salary         1
Experience     1
LeaveOrNot     1
dtype: int64

In [ ]:
data.isnull().sum().sum()

np.int64(3)

In [ ]:
data.isnull()

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,True,True,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False

In [ ]:
data[data['City']=='Amman']

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
0,8675,Bachelors,2017,Amman,34,Male,500.0,0.0,yes
4,4848,Masters,2017,Amman,24,Male,800.0,2.0,yes
5,6877,Bachelors,2016,Amman,22,Male,550.0,0.0,yes
8,8741,Bachelors,2016,Amman,23,Male,550.0,1.0,no
9,6789,Masters,2017,Amman,37,Male,900.0,2.0,no
10,9872,Masters,2012,Amman,27,Male,800.0,5.0,no
11,2017,Bachelors,2016,Amman,34,Male,700.0,3.0,no
16,6688,Bachelors,2014,Amman,34,Female,550.0,2.0,no
17,9764,Bachelors,2014,Amman,34,Male,600.0,4.0,no
18,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no
19,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no
20,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no
21,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no